- hosts: "{{ target }}" 
  remote_user: root
  tasks:
    - name: Download kafka
      unarchive:
        src: "http://www-eu.apache.org/dist/kafka/{{kafka_version}}/kafka_2.12-{{kafka_version}}.tgz"
        dest: /home/kafka/
        remote_src: yes
        owner: "kafka"
    - name: Creo link simbolico
      file:
        src: /home/kafka/kafka_2.12-{{kafka_version}}
        dest: /home/kafka/kafka
        owner: kafka
        group: kafka
        state: link
    - name: Modifico configurazione
      lineinfile:
        dest: /home/kafka/kafka/config/server.properties
        line: "delete.topic.enable = true"
        state: present
    - name: Istalla servizio zookeeper
      copy:
        src: zookeeper.service
        dest: /etc/systemd/system/
    - name: Istalla servizio kafka
      copy:
        src: kafka.service
        dest: /etc/systemd/system/
    - name: abilito e avvio il servizio kafka
      systemd:
        name: kafka
        state: started
        enabled: yes
    - name: abilito e avvio il servizio zookeeper
      systemd:
        name: zookeeper
        state: started
        enabled: yes
    - name: Regole firewall kafka
      firewalld:
        port: 9092/tcp
        permanent: yes
        state: enabled
    - name: Regole firewall zookeeper
      firewalld:
        port: 2181/tcp
        permanent: yes
        state: enabled
